#pragma once
int sum(int a, int b);
int sub(int a, int b);
int mul(int a, int b);
int divi(int a, int b);
int mod(int a, int b);
int minv(int a, int b);
int maxv(int a, int b);
int* sort_ary(int* ary, int n, int (*comp)(int, int));
void input_ary(int* ary, int n);
void print_str(char** ary, int n);
void print_float(float* ary, int n);
void print_ary(int* ary, int n);
int comp_asc(int a, int b);
int comp_dsc(int a, int b);
void swap(void* a, void* b, int n);
int comp_int(const void* a, const void* b);
int comp_char(const void* a, const void* b);
int comp_str(const void** a, const void** b);
int comp_float(const void* a, const void* b);